### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by koshMer** [tchlux/fmodpy#4]
I managed to uninstall and reinstall `fmodpy`. Now, all examples from last time work great -- via command line and my python editor.

However, when I try to run the following piece of code [tmm.txt](https://github.com/tchlux/fmodpy/files/6488376/tmm.txt)
with this python file:

```python
import fmodpy 
import numpy as np

code = fmodpy.fimport("tmm.f90")

n = np.array([1,2,1,2,1,2],dtype = float, order  = "F")
print(code.calc_k(630e-9,n,n))
```

i get the following error message:

```Python

Traceback (most recent call last):

  File "/home/johannes/Dokumente/Masterarbeit/Fortran/TMM/tmm_test/python_test_f90.py", line 38, in <module>
    print(code.calc_k(630e-9,n,n))

  File "/home/johannes/Dokumente/Masterarbeit/Fortran/TMM/tmm_test/tmm/__init__.py", line 85, in calc_k
    clib.c_calc_k(ctypes.byref(wavelength), ctypes.byref(n_dim_1), ctypes.c_void_p(n.ctypes.data), ctypes.byref(angle_dim_1), ctypes.c_void_p(angle.ctypes.data), ctypes.byref(k_dim_1), ctypes.c_void_p(k.ctypes.data))

  File "/home/johannes/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)

  File "/home/johannes/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: /home/johannes/Dokumente/Masterarbeit/Fortran/TMM/tmm_test/tmm/tmm.so: undefined symbol: c_calc_k

```  
Do you have a clue what's going on?

**Comment by tchlux** [comment]
This error generally means that the automatically generated Fortran `BIND(C)` wrapper did not successfully compile. Inside the generated python module directory there should be files `tmm/tmm_python_wrapper.py` and `tmm/tmm_c_wrapper.f90`. The function `c_calc_k` should be defined in `tmm_c_wrapper.f90`, and you can see how it works there.

Unfortunately I'm not sure why this is failing. When I download the `tmm.txt` file and rename it as `tmm.f90` locally, then run the python code you provided, it works on my macOS and Ubuntu test environments. To debug, I would start by using:

```python
code = fmodpy.fimport("tmm.f90", verbose=True)
```

Look at the output of that, see if there are any statements that look like errors.

Next, I would `cd` into the `tmm` directory that was generated by `fmodpy` and open the `tmm_python_wrapper.py` file. What happens when you execute that file? Does it compile a `.so` file every time you run it? That could mean that it is failing to compile a functioning `.so` file for some reason (related to the compiler / compilation settings).

**Comment by koshMer** [comment]
Thanks for the detailed info, I will be looking into it!

**Comment by koshMer** [comment]
Hi, the error for this particular file does not longer exist when i compile it. I am not sure why I got it in the first place. 
All i did in this 3 days was to restart my PC and reinstall your module, I am glad this works now :)
